# application.yml
server:
  port: 8001
spring:
  application:
    name: microservicecloud-dept
  datasource:
    url: jdbc:mysql://localhost:3306/DB01?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mavenMVC
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001-hystrix
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics

info:
  app.name: microservicecloud
  company.name: www.test.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
--
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/DB01?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mavenMVC
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/DB02?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mavenMVC
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1


